name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  CYPRESS_INSTALL_BINARY: 0
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build
        run: |
          npm ci
          npm run nx affected:build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Lint
        run: |
          npm ci
          npm run nx workspace-lint
          npm run nx affected:lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Test
        run: |
          npm ci
          npm run nx affected:test
