name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CYPRESS_INSTALL_BINARY: 0
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install
        run: |
          npm ci
      - name: Release
        run: |
          npm run build:all
          npm run release
